# Generated by Django 2.2.19 on 2022-12-05 20:55

from django.db import migrations

INITIAL_TAGS = [
    {"color": "orange", "name": "Завтрак", "slug": "breakfast"},
    {"color": "green", "name": "Обед", "slug": "lunch"},
    {"color": "purple", "name": "Ужин", "slug": "dinner"},
]


def add_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        new_tag = Tag(color=tag["color"], name=tag["name"], slug=tag["slug"])
        new_tag.save()


def remove_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        Tag.objects.get(slug=tag["slug"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_tags, remove_tags)]
